# Application server port
server.port=8081

# SQLite database configuration
spring.datasource.url=jdbc:sqlite:foodieexpress.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate settings
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Keep database open to avoid lock issues with SQLite
spring.datasource.hikari.maximum-pool-size=1
